/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pin.glb --shadow 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pin(props) {
  const { nodes, materials } = useGLTF('./assets/models/pin.glb')
  const positions = {}
  return (
    <group {...props} dispose={null}>
      <mesh scale={0.1} rotation={[0, -Math.PI / 2, 0]} geometry={nodes.Cube.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('./assets/models/pin.glb')
