/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\party.glb 
*/

import { useGLTF } from "@react-three/drei";
import { ShaderMaterial } from "three";
import { fragmentShader, vertexShader } from "../shaders/pool/shaders";
import {
  vertexShader as foliageVertexShader,
  fragmentShader as foliageFragmentShader,
} from '../shaders/foliage/shaders'
import { useFrame } from "@react-three/fiber";

import { RigidBody } from "@react-three/rapier";
import { waterHeight } from "../../utils";

import { Water } from "./Water";

export function FishingPool(props) {
  const { nodes, materials } = useGLTF("./assets/models/party.glb");

  const poolMaterial = new ShaderMaterial({
    vertexShader: vertexShader,
    fragmentShader: fragmentShader,
    uniforms: {
      map: { value: materials["Material.001"].map },
    },
    // transparent: true
  });

  const foliageMaterial = new ShaderMaterial({
    vertexShader: foliageVertexShader,
    fragmentShader: foliageFragmentShader,
    uniforms: {
      map: { value: materials.tree.map },
      time: { value: 0 },
      amplitude: { value: 5 },
    },
    transparent: true,
  });

  useFrame(({ clock}) => {
    foliageMaterial.uniforms.time.value = clock.getElapsedTime();
  });
  return (
    <group {...props} dispose={null}>
      <Water position={[0, waterHeight, 0]} scale={[15, 15, 15]} />
      <RigidBody type="fixed" colliders="trimesh">
        <mesh geometry={nodes.Cube.geometry} material={poolMaterial} />
      </RigidBody>
      <group
        position={[-7.55, 1.906, -3.614]}
        rotation={[0, -0.498, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh geometry={nodes.Plane001_2.geometry} material={foliageMaterial} />
      </group>
      <group
        position={[-9.564, 1.481, -0.772]}
        rotation={[0, -0.458, -Math.PI / 2]}
        scale={0.57}
      >
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh geometry={nodes.Plane002_2.geometry} material={foliageMaterial} />
      </group>
      <group
        position={[-5.586, 1.557, 1.959]}
        rotation={[0, 0.287, -Math.PI / 2]}
        scale={0.57}
      >
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh geometry={nodes.Plane003_2.geometry} material={foliageMaterial} />
      </group>
      <group
        position={[5, 2, 3.313]}
        rotation={[0, 0.431, -Math.PI / 2]}
        scale={0.57}
      >
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane004_2.geometry}
          material={materials["tree.001"]}
        />
      </group>
      <group
        position={[5.021, 2.012, -4.422]}
        rotation={[0, -0.502, -Math.PI / 2]}
        scale={1.039}
      >
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane005_2.geometry}
          material={materials["tree.001"]}
        />
      </group>
      <group
        position={[-6.692, 1.481, 3.646]}
        rotation={[0, 0.327, -Math.PI / 2]}
        scale={0.57}
      >
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh geometry={nodes.Plane006_2.geometry} material={foliageMaterial} />
      </group>
    </group>
  );
}

useGLTF.preload("./assets/models/party.glb");
