/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\hook.glb 
*/

import { useGLTF } from '@react-three/drei'

export function Hook(props) {
  const { nodes, materials } = useGLTF('./assets/models/hook.glb')
  return (
    <group scale={0.15} {...props} rotation={[0, -Math.PI /2,0]} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('./assets/models/hook.glb')
